import localFont from "next/font/local";
import "./globals.css";
import { parseCookies } from 'nookies';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "FinanceForeCast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { nonce } = parseCookies();
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        

        {children}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `console.log("Script ejecutado en el layout");`,
          }}
        />
      </body>
    </html>
  );
}
