// src/app/layout.server.tsx

export const metadata = {
    title: "FinanceForeCast",
    description: "Generated by create next app",
  };
  
  export default function Layout({ children }) {
    return (
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    );
  }
  